### ISSUE TITLE
What is the shortcut key or how do I assign it?

### ISSUE THREAD

**Issue by linker-err0r** [minosvasilias/godot-copilot#11]
I looked at the docs and it just says "Use the assigned shortcut key" or something to that effect, but it isn't clear to me what that is or how to assign it. A little help?

**Comment by minosvasilias** [comment]
For others getting here via search, the current shortcut is shown and editable in the Copilot panel that is added when enabling the plugin:
<img width="332" alt="Screenshot 2024-03-13 at 20 15 00" src="https://github.com/minosvasilias/godot-copilot/assets/44006014/a618bec5-ae7f-4943-aa3e-e53f8285ff02">
