### ISSUE TITLE
Get error on v1.0.1

### ISSUE THREAD

**Issue by windyjl** [minosvasilias/godot-copilot#16]
res://addons/copilot/GithubCopilot.gd:167 - Invalid call. Nonexistent function 'has' in base 'Nil'.

**Comment by windyjl** [comment]
on_request_completed get "bad request",and stuck the editor.

**Comment by windyjl** [comment]
My bad. Seems i didn't follow the setup exectly

**Comment by dhudsmith** [comment]
I get this error as well using github copilot. What was the resolution? 
`res://addons/copilot/GithubCopilot.gd:167 - Invalid call. Nonexistent function 'has' in base 'Nil'.`
