### ISSUE TITLE
Dangling HttpRequests

### ISSUE THREAD

**Issue by 73v3** [minosvasilias/godot-copilot#3]
Thanks so much for making this addon!

I'm messing around with repurposing the GPT side of the code and noticed

`var http_request = HTTPRequest.new()
	add_child(http_request)
	http_request.connect("request_completed",Callable(self,"on_request_completed").bind(_prompt, _suffix))
	var json_body = JSON.stringify(body)
	var buffer = json_body.to_utf8_buffer()`

Correct me if I'm wrong, but each completion will leave its own http_request node dangling in the editor tree after use. To address this, I bind the http_request as follows:

`http_request.connect("request_completed",on_request_completed.bind(prompt, http_request))`

and then at the very end of on_request_completed:

`if is_instance_valid(http_request):
		http_request.queue_free()`

Also, 
`var buffer = json_body.to_utf8_buffer()`

doesn't seem to be used.

Reality check: I'm great at giving bad advice and putting my foot in my mouth. So I could be totally off base here.

Regardless, I really love all the work you are doing bringing AI to Godot. Thanks again!

**Comment by minosvasilias** [comment]
Hey, thanks a bunch for the nice words and for pointing this out!
You're completely right on both issues of course. That dangling request node is a pretty dumb oversight.

I'll probably address this on the weekend. Otherwise feel free to open a PR if you want it fixed asap and i'll get it merged. 👍

**Comment by minosvasilias** [comment]
Addressed here: #4, #5 👍
