### ISSUE TITLE
Great idea, kind of not a very good name

### ISSUE THREAD

**Issue by servel333** [minosvasilias/godot-copilot#6]
I don't mean this to be mean or disrespectful,

but when I read "Copilot", I assumed it integrated GitHub Copilot into Godot, not OpenAIs API. That's a bit misleading.

**Comment by minosvasilias** [comment]
Well, GitHub Copilot is also using OpenAI models behind the scenes, so in that sense the approach is the same. If the GitHub Copilot product itself offered an API offering another layer of abstraction, it'd make sense to support it, but it doesn't.

So i always considered "Copilot" to be a pretty generic name for AI-assistants. And we see the same naming scheme with things like Windows Copilot.

**Comment by servel333** [comment]
I had assumed they just provided a regular API, but apparently not. Wow. That's really disappointment. I'm paying for copilot, and it would have been nice to use what I'm already paying for.

Yea, It's a bit confusing still, but maybe that can be addressed in the README.md?

**Comment by servel333** [comment]
It says OpenAI in the description, so I guess that's probably good enough. Thanks.
